

AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  DisabledByDefault: false
  TargetRubyVersion: 2.7
  NewCops: enable

Style/BlockDelimiters:
  Enabled: false
# Checks if uses of quotes match the configured preference.
Style/StringLiterals:
  Enabled: false
