inherit_mode:
  merge:
    - Exclude
require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
Layout/HashAlignment:
  EnforcedHashRocketStyle: [ key, table ]
  EnforcedColonStyle: [ key, table ]
Layout/LineLength:
  Max: 50
