name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        
    - name: Run RuboCop
      run: |
        bundle install
        bundle exec rubocop --auto-correct
