name: Linting

on: [push]

jobs:
  test:
    name: Rubocop
    runs-on: ubuntu-18.04
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Ruby 2.7.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Bundle cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
       
      - name: Run Rubocop
        run: bundle exec rubocop --parallel   
